name: Extraire le site

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Extraire le fichier ZIP
        run: |
          unzip -o "benediction-charigufi-site-final.zip" -d .

      - name: Supprimer le ZIP
        run: |
          rm "benediction-charigufi-site-final.zip"

      - name: Enregistrer les fichiers extraits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Extraction du site"
          git push
